### ISSUE TITLE
bug: link broken

### ISSUE THREAD

**Issue by weerdy15** [sapphiredev/website#166] opened 2022-05-13 14:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Link with text `the contribution guide` in [General/Welcome#contributing](https://www.sapphirejs.dev/docs/General/Welcome#contributing) is broken.

### Steps To Reproduce

Go [here](https://www.sapphirejs.dev/docs/General/Welcome#contributing) and click on blue text `the contribution guide`

### Expected behavior

Link redirects me to the contribution guide

**Comment by RealShadowNova** [comment] 2022-05-13 17:19
I see the issue is that the file is literally missing from the [sapphiredev/readme](https://github.com/sapphiredev/website) repository. Most likely an oversight and can easily be fixed by the file being added.

**Comment by favna** [comment] 2022-05-13 21:24
https://github.com/sapphiredev/.github/blob/main/.github/CONTRIBUTING.md should be linked instead

**Closed** 2022-05-14 06:47 UTC
Labels: Bug: Confirmed
